// Données mock / seed pour le développement
// TODO: remplacer par Firestore — voir Antigravity.md

import type {
  Product,
  Tool,
  ChatSession,
  CeoAnalysis,
} from "./types";

const now = new Date().toISOString();

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "T-shirt chanvre bio",
    slug: "t-shirt-chanvre-bio",
    description: "T-shirt 100% chanvre biologique, coupe unisexe.",
    category: "textile",
    status: "published",
    price: 3900,
    currency: "CAD",
    stock: 120,
    imageUrl: "",
    tags: ["chanvre", "bio", "textile"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
  {
    id: "p2",
    name: "Sac à dos écologique",
    slug: "sac-a-dos-ecologique",
    description: "Sac à dos en fibres recyclées.",
    category: "accessoire",
    status: "published",
    price: 8900,
    currency: "CAD",
    stock: 45,
    tags: ["accessoire", "écolo"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
  {
    id: "p3",
    name: "Crème hydratante CBD",
    slug: "creme-hydratante-cbd",
    description: "Crème visage enrichie au CBD.",
    category: "cosmetique",
    status: "draft",
    price: 4500,
    currency: "CAD",
    stock: 0,
    tags: ["cosmétique", "cbd"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
  {
    id: "p4",
    name: "Barre énergétique chanvre",
    slug: "barre-energetique-chanvre",
    description: "Barre protéinée aux graines de chanvre.",
    category: "alimentaire",
    status: "published",
    price: 350,
    currency: "CAD",
    stock: 500,
    tags: ["alimentaire", "protéine"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
  {
    id: "p5",
    name: "Bonnet tricoté",
    slug: "bonnet-tricote",
    description: "Bonnet chaud en laine mélangée chanvre.",
    category: "textile",
    status: "archived",
    price: 2900,
    currency: "CAD",
    stock: 12,
    tags: ["textile", "hiver"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
  {
    id: "p6",
    name: "Huile essentielle relaxante",
    slug: "huile-essentielle-relaxante",
    description: "Mélange d'huiles pour détente.",
    category: "cosmetique",
    status: "published",
    price: 5900,
    currency: "USD",
    stock: 80,
    tags: ["cosmétique", "détente"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
  {
    id: "p7",
    name: "Gourde isotherme",
    slug: "gourde-isotherme",
    description: "Gourde en inox, garde le froid 24h.",
    category: "accessoire",
    status: "draft",
    price: 3200,
    currency: "EUR",
    stock: 200,
    tags: ["accessoire", "réutilisable"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
  {
    id: "p8",
    name: "Coffret découverte",
    slug: "coffret-decouverte",
    description: "Assortiment de produits phares.",
    category: "autre",
    status: "published",
    price: 12900,
    currency: "CAD",
    stock: 30,
    tags: ["coffret", "cadeau"],
    createdAt: now,
    updatedAt: now,
    createdBy: "seed",
  },
];

export const SEED_TOOLS: Tool[] = [
  {
    id: "t1",
    name: "Analytics Dashboard",
    description: "Tableau de bord des ventes en temps réel.",
    type: "url",
    href: "https://analytics.example.com",
    icon: "📈",
    enabled: true,
    order: 1,
    createdAt: now,
  },
  {
    id: "t2",
    name: "Gestion des stocks",
    description: "Suivi et réapprovisionnement.",
    type: "internal",
    href: "/produits",
    icon: "📦",
    enabled: true,
    order: 2,
    createdAt: now,
  },
  {
    id: "t3",
    name: "Générateur de descriptions",
    description: "Rédaction assistée par IA.",
    type: "internal",
    href: "/assistant",
    icon: "✍️",
    enabled: true,
    order: 3,
    createdAt: now,
  },
  {
    id: "t4",
    name: "Export comptable",
    description: "Export des données vers le logiciel comptable.",
    type: "api",
    href: "/api/export",
    icon: "🧾",
    enabled: false,
    order: 4,
    createdAt: now,
  },
  {
    id: "t5",
    name: "Support client",
    description: "Accès à la plateforme de tickets.",
    type: "url",
    href: "https://support.example.com",
    icon: "🎧",
    enabled: true,
    order: 5,
    createdAt: now,
  },
];

export const SEED_CHAT_SESSION: ChatSession = {
  id: "c1",
  title: "Idées de descriptions produits",
  ownerUid: "seed",
  createdAt: now,
  updatedAt: now,
  messages: [
    {
      id: "m1",
      role: "user",
      content: "Peux-tu m'aider à rédiger une description pour un t-shirt en chanvre ?",
      createdAt: now,
    },
    {
      id: "m2",
      role: "assistant",
      content:
        "Bien sûr ! Voici une proposition : « Adoptez le confort naturel avec notre t-shirt 100% chanvre biologique... »",
      createdAt: now,
    },
  ],
};

export const SEED_CEO_ANALYSIS: CeoAnalysis = {
  generatedAt: now,
  period: "30d",
  metrics: [
    {
      id: "cm1",
      label: "Chiffre d'affaires",
      value: 4520000,
      unit: "currency",
      trend: "up",
      changePct: 12.4,
    },
    {
      id: "cm2",
      label: "Commandes",
      value: 342,
      unit: "count",
      trend: "up",
      changePct: 8.1,
    },
    {
      id: "cm3",
      label: "Taux de conversion",
      value: 3.2,
      unit: "percent",
      trend: "flat",
      changePct: 0.2,
    },
    {
      id: "cm4",
      label: "Retours",
      value: 5.6,
      unit: "percent",
      trend: "down",
      changePct: -1.3,
    },
  ],
  insights: [
    {
      id: "ci1",
      title: "Croissance soutenue du textile",
      summary:
        "La catégorie textile représente 48% du CA ce mois-ci, en hausse de 12%. Envisager d'élargir la gamme.",
      severity: "info",
      createdAt: now,
    },
    {
      id: "ci2",
      title: "Rupture de stock imminente",
      summary:
        "Le produit « Bonnet tricoté » a un stock faible (12 unités) malgré une forte demande saisonnière.",
      severity: "warning",
      createdAt: now,
    },
  ],
};
